name: "tesouro_dbt"
version: "1.0.0"

profile: "tesouro_dbt"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  tesouro_dbt:

    bridge:
      +materialized: table
      +tags:
        - bridge

    pit:
      +materialized: table
      +tags:
        - pit

    marts:
      +materialized: table
      +tags:
        - gold