alerts:

  slack:
    enabled: true
    channel: "data_quality_notification"
    webhook_secret_scope: "lakehouse_lab"
    webhook_secret_key: "slack_data_quality_webhook"

  default:
    ERROR:
      emails:
        - "pradovalmur@gmail.com"

    WARNING:
      emails:
        - "pradovalmur@gmail.com"

  pipelines:
    tesouro_direto_pipeline:
      ERROR:
        emails:
          - "pradovalmur@gmail.com"
          - "pradovalmur@outlook.com"

      WARNING:
        emails:
          - "pradovalmur@gmail.com"

  tasks:
    quality_bronze_operacoes:
      ERROR:
        emails:
          - "pradovalmur@gmail.com"

    quality_bronze_investidores:
      ERROR:
        emails:
          - "pradovalmur@gmail.com"