hubs:
  hubInvestidor:
    source_table: "lakehouse_lab.bronze.investidores"
    target_table: "lakehouse_lab.silver.hubInvestidor"
    hash_key: "hubInvestidorHk"
    business_key:
      - "codigoDoInvestidor"

  hubTitulo:
    source_table: "lakehouse_lab.bronze.operacoes"
    target_table: "lakehouse_lab.silver.hubTitulo"
    hash_key: "hubTituloHk"
    business_key:
      - "tipoTitulo"

links:
  linkInvestidorTituloOperacao:
    source_table: "lakehouse_lab.bronze.operacoes"
    target_table: "lakehouse_lab.silver.linkInvestidorTituloOperacao"
    hash_key: "linkInvestidorTituloOperacaoHk"
    business_keys:
      investidor:
        hub_key: "hubInvestidorHk"
        keys:
          - "codigoDoInvestidor"
      titulo:
        hub_key: "hubTituloHk"
        keys:
          - "tipoTitulo"
    link_keys:
      - "codigoDoInvestidor"
      - "tipoTitulo"
      - "dataDaOperacao"

satellites:
  satInvestidor:
    source_table: "lakehouse_lab.bronze.investidores"
    target_table: "lakehouse_lab.silver.satInvestidor"
    hash_key: "hubInvestidorHk"
    parent_keys:
      - "codigoDoInvestidor"
    attributes:
      - "dataDeAdesao"
      - "estadoCivil"
      - "genero"
      - "profissao"
      - "idade"
      - "ufDoInvestidor"
      - "cidadeDoInvestidor"
      - "paisDoInvestidor"
      - "situacaoDaConta"
      - "operou12Meses"

  satOperacao:
    source_table: "lakehouse_lab.bronze.operacoes"
    target_table: "lakehouse_lab.silver.satOperacao"
    hash_key: "linkInvestidorTituloOperacaoHk"
    parent_keys:
      - "codigoDoInvestidor"
      - "tipoTitulo"
      - "dataDaOperacao"
    attributes:
      - "dataDaOperacao"
      - "quantidade"
      - "valorDaOperacao"
      - "tipoDaOperacao"

quality:
  hubs:
    hubInvestidor:
      table: "lakehouse_lab.silver.hubInvestidor"
      hash_key: "hubInvestidorHk"
      business_keys:
        - "codigoDoInvestidor"

    hubTitulo:
      table: "lakehouse_lab.silver.hubTitulo"
      hash_key: "hubTituloHk"
      business_keys:
        - "tipoTitulo"

  links:
    linkInvestidorTituloOperacao:
      table: "lakehouse_lab.silver.linkInvestidorTituloOperacao"
      hash_key: "linkInvestidorTituloOperacaoHk"
      hub_keys:
        - "hubInvestidorHk"
        - "hubTituloHk"

  satellites:
    satInvestidor:
      table: "lakehouse_lab.silver.satInvestidor"
      hash_key: "hubInvestidorHk"
      required_columns:
        - "hubInvestidorHk"
        - "loadTs"

    satOperacao:
      table: "lakehouse_lab.silver.satOperacao"
      hash_key: "linkInvestidorTituloOperacaoHk"
      required_columns:
        - "linkInvestidorTituloOperacaoHk"
        - "loadTs"
        - "valorDaOperacao"
        - "dataDaOperacao"