name: Sync Databricks Git Folder

on:
  push:
    branches:
      - main
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Update Databricks Git Folder
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks repos update "/Workspace/Users/pradovalmur@gmail.com/Databricks_lab" --branch main